"""add asset_snapshots table

Revision ID: 6dd4b35cdb82
Revises: 91842707d7df
Create Date: 2026-09-29 14:50:25.799336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dd4b35cdb82'
down_revision: Union[str, Sequence[str], None] = '91842707d7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'trade_date', name='uq_asset_snapshot')
    )
    op.create_index(op.f('ix_asset_snapshots_key'), 'asset_snapshots', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_snapshots_key'), table_name='asset_snapshots')
    op.drop_table('asset_snapshots')
    # ### end Alembic commands ###
