"""add document_chunks table

Revision ID: 91842707d7df
Revises: 9c1a9382552c
Create Date: 2026-09-29 09:19:03.213436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91842707d7df'
down_revision: Union[str, Sequence[str], None] = '9c1a9382552c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.String(length=300), nullable=False),
    sa.Column('document_id', sa.String(length=200), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('text', sa.String(length=4000), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_doc_chunk')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_doc_type'), 'document_chunks', ['doc_type'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_symbol'), 'document_chunks', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_symbol'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_doc_type'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
